name: client test

on:
  push:
    branches: [ HW3 ]
    paths-ignore: [ '**/readme.md' ]
  pull_request:
    branches: [ HW3 ]

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build containers
        run: docker-compose build
    
      - name: Up containers
        run: docker-compose up -d
    
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.2'
          cache: 'npm'
          cache-dependency-path: ./client/package-lock.json
        
      - name: Clear install
        run: npm --prefix client ci && npx playwright install && npx playwright install-deps
        
      - name: Build
        run: npm --prefix client run build

      - name: Run tests
        run: npm --prefix client run test

      - name: Stop containers
        if: always()
        run: docker-compose down

