name: client test

on:
  push:
    branches: [ HW3 ]
    paths-ignore: [ '**/readme.md' ]
  pull_request:
    branches: [ HW3 ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json
      - name: Install dependencies
        run: npm --prefix client install
#       - name: Install playwright
#         run: npx install playwright
      - name: Start deployment
        run: npm --prefix client start
      - name: Run unit tests
        run: npm --prefix client src/test/unit
      - name: Run e2e tests
        run: npm --prefix client src/test/e2e
