name: server test

on:
  push:
    branches: [ HW3 ]
    paths-ignore: [ '**/readme.md' ]
  pull_request:
    branches: [ HW3 ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11s
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -f backend -B package --file pom.xml
